### ISSUE TITLE
gnome 3.30 support?

### ISSUE THREAD

**Issue by weylara** [BlinkBP/walkpaper#11]
Would it be possible to update the walkpaper pluging so that it can be used with gnome 3.30? Right now it only shows a unspecific error. And what about trying to get it to the main functionality of gnome so that there would even not be the need for a plugin (I imagine different wallpapers is nothing too exotic)? Thx. a lot!

**Comment by Arquanite** [comment]
To make it work on new gnome replace `global.screen` by `global.workspace_manager` in `~/.local/share/gnome-shell/extensions/walkpaper@walkpaper.blinkbp.github.com/extension.js`
