### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by tommly** [BlinkBP/walkpaper#12]
Has this project been abandoned? Looks like no updates in two years.

-Tom

**Comment by Eren-is** [comment]
Thanks @tommly!
Your message was what got me to finally sit down and fix some of the problems with the extension.
I will post newest version to GNOME Extensions tomorrow so everyone can install and/or update the extension automatically. It could take few days for them to review it though.

**Comment by tommly** [comment]
Great, thanks. I'm glad to see this continuing.

-Tom
