### ISSUE TITLE
Gnome 40 Update

### ISSUE THREAD

**Issue by LudovicoPiero** [BlinkBP/walkpaper#16]
is there an update for gnome 40?
i've tried to make file but its not working in my gnome 40.

**Comment by somemarco** [comment]
Is the gnome 40 update something which is on the roadmap? respectively would you accept PRs?

**Comment by mlmilliman** [comment]
I was able to get the extension to function by allowing GNOME 40 to be supported plus changing a property in the settings window. The preferences pane still has errors. I don't know GTK so I don't think I can fix them on my own. Someone that knows GTK3 can probably fix them in a couple of minutes. It looks like the author has abandoned this extension though. Too bad because it is a nice workaround for a feature that should already be in GNOME.

**Comment by geekysquirrel** [comment]
@mlmilliman can you share your fix for the setting window please?

**Comment by geekysquirrel** [comment]
fwiw my workaround so far is to just update the version in `metadata.json`. I can't find decent documentation for updating from Gtk3 to Gtk4 so I just don't touch the broken settings GUI but update the values manually using `dconf-editor`.
The settings are located in `/org/gnome/shell/extensions/walkpaper/`.
Restarting gnome shell alone didn't do it for me but logging out/back in again worked.

**Comment by mlmilliman** [comment]
So far I made two changes to the extension. My first edit was in metadata.json to support GNOME 40:
The line `"40"` was added after `"3.32",` Note I added the comma after the quote mark. The second edit was in the file prefs.js on line 115 where it now reads `{ shadow-type: GTK_SHADOW_IN }`. I rebuilt the extension and reinstalled it before restarting GNOME. Those were enough changes to get the thing running again, but you cannot bring up the settings panel. The next error is somewhere in this _init function but I can't find it yet. Perhaps someone more familiar with GTK3 can figure it out and suggest a fix.

**Comment by geekysquirrel** [comment]
Thanks for sharing this - I even struggled to find documentation how to change the `prefs.js` file.
Let's hope somebody else can pick it up from here 🤞

**Comment by mcoyle1960** [comment]
Nice job @mlmilliman, your tweaks got it working. It's a little glitchy on the dissolve from one wallpaper to the next, but it works.

**Comment by mlmilliman** [comment]
I'm trying to learn enough GTK3+ to figure out what's going on with the preferences screen. My assumption is that there is deprecated code in `prefs.js` that must be corrected. I have a friend that I'll ask for assistance.

**Comment by Eren-is** [comment]
I finally have some new hardware on which I plan to run mainly Gnome. So I'm going to work on fixing the extension for Gnome 40.
Finding workarounds for GTK3 code not working on new GTK4 will be a hassle.

@puravida-marco I'm open to PRs.

If anyone wants to play around with getting the prefs.js working here are pretty good docs for [js GTK4](https://gjs-docs.gnome.org/gtk40~4.2.1/).
And here for [js GTK3](https://gjs-docs.gnome.org/gtk30~3.24.30/) for comparison.

@mlmilliman the second error, after the GTK_SHADOW_IN, is connected with Grid not inheriting from the Gtk.Container in GTK4 so there is no simple "this.add(widget)" now. That's what I gathered so far.

**Comment by Eren-is** [comment]
Hey.
Pushed a commit adding support for GNOME 40 and Gtk 4. Let me know if there are any issues.

**Comment by mlmilliman** [comment]
The changes work perfectly including the preferences pane. I am not familiar with GTK at all so I was really hacking at the code to fix the issues. @BlinkBP is right that there is no simple replacement for this.add(widget). This is where I ran into the problem. Thanks for fixing something that should be built into GNOME 40. Seems like the GNOME developers don't pay attention to what the other OS window managers are doing.
