### ISSUE TITLE
Documentation and/or prefs

### ISSUE THREAD

**Issue by eliotb** [BlinkBP/walkpaper#2]
At least needs better explanation of what the entries in the prefs window are.
The list is titled "Workspace Names", but in fact it should be a list of absolute paths to images to use for the corresponding workspace.

So, I suggest changing that title to "List of workspace background images".  It would be good to have a file picker for each one. Maybe something like the Tweak Tool "Startup Applications" tab?

**Comment by eliotb** [comment]
Another way to set up backgrounds would be for this extension to store the current background before switch to a different workspace (I don't know if there is a suitable event).
Equivalent would be to store background for previous workspace, before switching to new for current workspace.

The background for a given workspace would be chosen using the standard static background chooser.
Then this extension wouldn't need any 'prefs'

**Comment by Eren-is** [comment]
Addressed file picking in d820c017927d73e5455c11be105ea51718591ddf.  
Addressed saving current background on workspace change in #5.

**Comment by Eren-is** [comment]
I plan on working more on the prefs. Maybe add an icon for every workspace and a small preview. 
Any suggestions and such are welcome.
